name: F1nnyMinigames
main: me.beshenii.project.Plugin
version: "1.0"
api-version: 1.20

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.1

commands:
  host:
    permission: minecraft.*
    permission-message: "Нет прав."

