name: F1nnyMinigames
main: me.beshenii.project.Plugin
version: "1.0"
api-version: 1.20

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0
  - org.jetbrains.kotlinx:kotlinx-serialization-json:2.0.20-Beta1

softdepend:
  - Authy

commands:
  item:
    description: "Получить игровой предмет"
    permission: minecraft.*
    permission-message: "Нет прав."
    
  crafts:
    description: "Обновить игровые крафты"
    permission: minecraft.*
    permission-message: "Нет прав."

